# Generated by Django 2.2.5 on 2019-09-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='id',
        ),
        migrations.AlterField(
            model_name='storage',
            name='post_link',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
