# Generated by Django 2.2.5 on 2019-10-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20191004_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagevk',
            name='post_time',
        ),
    ]
