# Generated by Django 2.2.5 on 2019-10-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='id',
        ),
        migrations.AlterField(
            model_name='statistics',
            name='stat_date',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
