# Generated by Django 2.2.5 on 2019-10-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_auto_20191009_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='post_date',
            field=models.DateTimeField(),
        ),
    ]
