# Generated by Django 2.2.5 on 2019-10-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_auto_20191014_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageVK',
            fields=[
                ('slug', models.SlugField(unique=True)),
                ('post_query', models.TextField()),
                ('post_type', models.TextField()),
                ('post_ownert', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('post_link', models.TextField(primary_key=True, serialize=False)),
                ('post_id', models.TextField()),
                ('post_owner', models.TextField()),
                ('post_text', models.TextField()),
                ('post_score', models.TextField()),
                ('post_keyword', models.TextField()),
                ('post_mark', models.TextField()),
                ('post_len', models.TextField()),
                ('post_category', models.TextField()),
                ('post_textp', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.AlterField(
            model_name='statistics1',
            name='stat_date',
            field=models.TextField(),
        ),
    ]
