# Generated by Django 2.2.5 on 2019-10-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_auto_20191014_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagevk',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storagevk',
            name='post_link',
            field=models.TextField(),
        ),
    ]
