# Generated by Django 2.2.5 on 2019-10-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_auto_20191014_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagevk',
            name='id',
        ),
        migrations.AlterField(
            model_name='storagevk',
            name='post_link',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storagevk',
            name='slug',
            field=models.SlugField(),
        ),
    ]
