# Generated by Django 2.2.5 on 2019-10-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_auto_20191014_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagevk',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
