# Generated by Django 2.2.5 on 2019-10-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_auto_20191014_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics1',
            name='stat_id',
        ),
        migrations.AlterField(
            model_name='statistics1',
            name='stat_date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
