# Generated by Django 2.2.5 on 2019-10-17 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_auto_20191017_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics1',
            new_name='Statistics2',
        ),
    ]
