# Generated by Django 2.2.5 on 2019-10-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_auto_20191017_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics2',
            name='name',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistics2',
            name='stat_date',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
