# Generated by Django 2.2.5 on 2019-10-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_auto_20191017_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='name',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_date',
        ),
        migrations.AddField(
            model_name='statistics',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
