# Generated by Django 2.2.5 on 2019-10-17 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_auto_20191017_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='stat_adv',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_azs',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_comment',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_common',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_count',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_danger',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_event',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_fin',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_kvn',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_media',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_post',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_secondary',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_social',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_sport',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_success',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_tna',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_vak',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='stat_warning',
        ),
    ]
