# Generated by Django 2.2.5 on 2019-10-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_auto_20191017_0220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
